version: '3'
services:
    msfconsole:
        image: fcolista/alpine-metasploit
        # build: ../../Dockerfiles/metasploit-framework
        # environment:
            # DATABASE_URL: postgres://postgres@db:5432/msf
        depends_on:
            - db
        ports:
            - 4444:4444
        volumes:
            - $HOME/.msf4:/home/msf/.msf4
        network_mode: bridge
    db:
        image: postgres:9-alpine
        volumes:
            - pg_data:/var/lib/postgresql/data
        network_mode: bridge
volumes:
    pg_data:
        driver: local
